// <auto-generated />
using ApiLesson4.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiLesson4.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20260507113236_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("ApiLesson4.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Population")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The city that never sleeps",
                            Name = "New York",
                            Population = 8000000
                        },
                        new
                        {
                            Id = 2,
                            Description = "The city of love",
                            Name = "Paris",
                            Population = 2000000
                        },
                        new
                        {
                            Id = 3,
                            Description = "The city of the rising sun",
                            Name = "Tokyo",
                            Population = 9000000
                        });
                });

            modelBuilder.Entity("ApiLesson4.Entities.LandMark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("LandMarks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "A symbol of freedom",
                            IsDeleted = false,
                            Name = "Statue of Liberty"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            Description = "A global cultural icon of France",
                            IsDeleted = false,
                            Name = "Eiffel Tower"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            Description = "A communications and observation tower",
                            IsDeleted = false,
                            Name = "Tokyo Tower"
                        });
                });

            modelBuilder.Entity("ApiLesson4.Entities.LandMark", b =>
                {
                    b.HasOne("ApiLesson4.Entities.City", "City")
                        .WithMany("LandMarks")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("ApiLesson4.Entities.City", b =>
                {
                    b.Navigation("LandMarks");
                });
#pragma warning restore 612, 618
        }
    }
}
