// <auto-generated />
using CarCatalogApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarCatalogApi.Migrations
{
    [DbContext(typeof(CarCatalogDbContext))]
    [Migration("20260521180407_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("CarCatalogApi.Entities.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("YearFrom")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId", "Name")
                        .IsUnique();

                    b.ToTable("CarModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BodyType = "Sports Car",
                            ManufacturerId = 1,
                            Name = "Corvette",
                            YearFrom = 1953
                        },
                        new
                        {
                            Id = 2,
                            BodyType = "Muscle Car",
                            ManufacturerId = 1,
                            Name = "Camaro",
                            YearFrom = 1966
                        },
                        new
                        {
                            Id = 3,
                            BodyType = "Sedan",
                            ManufacturerId = 2,
                            Name = "Corolla",
                            YearFrom = 1966
                        });
                });

            modelBuilder.Entity("CarCatalogApi.Entities.CarSubModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EngineCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HorsePower")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarModelId", "Name")
                        .IsUnique();

                    b.ToTable("CarSubModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarModelId = 1,
                            EngineCode = "6.2L V8",
                            HorsePower = 490,
                            Name = "LT2"
                        },
                        new
                        {
                            Id = 2,
                            CarModelId = 1,
                            EngineCode = "5.5L V8",
                            HorsePower = 670,
                            Name = "Z06"
                        },
                        new
                        {
                            Id = 3,
                            CarModelId = 2,
                            EngineCode = "6.2L V8",
                            HorsePower = 455,
                            Name = "SS"
                        },
                        new
                        {
                            Id = 4,
                            CarModelId = 3,
                            EngineCode = "1.8L Hybrid",
                            HorsePower = 138,
                            Name = "Hybrid"
                        });
                });

            modelBuilder.Entity("CarCatalogApi.Entities.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FoundedYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "United States",
                            FoundedYear = 1911,
                            Name = "Chevrolet"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Japan",
                            FoundedYear = 1937,
                            Name = "Toyota"
                        });
                });

            modelBuilder.Entity("CarCatalogApi.Entities.CarModel", b =>
                {
                    b.HasOne("CarCatalogApi.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Models")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("CarCatalogApi.Entities.CarSubModel", b =>
                {
                    b.HasOne("CarCatalogApi.Entities.CarModel", "CarModel")
                        .WithMany("SubModels")
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarModel");
                });

            modelBuilder.Entity("CarCatalogApi.Entities.CarModel", b =>
                {
                    b.Navigation("SubModels");
                });

            modelBuilder.Entity("CarCatalogApi.Entities.Manufacturer", b =>
                {
                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
